CREATE DATABASE MERCEARIA

USE MERCEARIA

CREATE TABLE CLIENTE
(
CD_CLIENTE INT,
NOME_CLIENTE VARCHAR(50),
DT_NASCIMENTO_CLIENTE DATETIME, 
CONSTRAINT PK_CD_CLIENTE PRIMARY KEY (CD_CLIENTE)
)



CREATE TABLE PEDIDO
(
CD_PEDIDO INT,
DT_PRDIDO DATETIME,
VL_PEDIDO FLOAT, 
CD_CLIENTE_PEDIDO INT, 
CONSTRAINT PK_CD_PEDIDO PRIMARY KEY (CD_PEDIDO),
CONSTRAINT FK_CD_PEDIDO FOREIGN KEY (CD_CLIENTE_PEDIDO)
REFERENCES CLIENTE(CD_CLIENTE)
) 



INSERT INTO CLIENTE VALUES (1,'XPTO','06-05-1988');


SELECT * FROM CLIENTE


INSERT INTO CLIENTE VALUES (2,'XPTO_TESTE','06-01-2000');
INSERT INTO CLIENTE VALUES (3,'XPTO_ULTIMATE','06-05-1989');

SELECT * FROM CLIENTE

UPDATE CLIENTE

SET NOME_CLIENTE = 'ANOTHER FUCK'
WHERE CD_CLIENTE = 1

SELECT * FROM CLIENTE

UPDATE CLIENTE

SET DT_NASCIMENTO_CLIENTE = '09-06-2000',
NOME_CLIENTE = 'AGATHA'
WHERE CD_CLIENTE = 2







